import random

recipes = {
    "Sambar": ["toor dal", "tamarind", "drumstick", "curry leaves", "mustard seeds"],
    "Rasam": ["tamarind", "tomato", "pepper", "cumin", "curry leaves"],
    "Avial": ["curd", "coconut", "carrot", "beans", "drumstick"],
    "Aloo Bhindi": ["potato", "ladyfinger", "onion"],
    "Dal Fry": ["toor dal", "onion", "tomato", "ghee"],
    "Paneer Lababdar": ["paneer", "onion", "tomato", "cream"],
    "Jeera Rice": ["rice", "cumin seeds", "ghee"],
    "Veg Kadai": ["capsicum", "onion", "tomato", "peas"],
    "Mix Veg Curry": ["carrot", "beans", "peas", "onion", "tomato"],
    "Lauki Chana Dal": ["bottle gourd", "chana dal", "onion", "tomato"],
    "Palak Rice": ["rice", "spinach", "onion"],
    "Paneer Korma": ["paneer", "coconut", "onion", "tomato"],
    "Tinda Masala": ["tinda", "onion", "tomato"],
    "Aloo Gobi": ["potato", "cauliflower", "onion", "tomato"],
    "Masala Khichdi": ["rice", "moong dal", "onion", "tomato"],
    "Karela Sabzi": ["bitter gourd", "onion"],
    "Vegetable Fried Rice": ["rice", "carrot", "peas", "capsicum"],
    "Paneer Tikka Masala": ["paneer", "onion", "capsicum", "tomato"],
    "Rajma Masala": ["kidney beans", "onion", "tomato"],
    "Dal Tadka": ["toor dal", "onion", "tomato", "ghee"],
    "Cabbage Rice": ["rice", "cabbage", "onion"],
    "Veg Jalfrezi": ["carrot", "capsicum", "beans", "onion", "tomato"],
    "Methi Rice": ["rice", "fenugreek leaves", "onion"],
    "Palak Paneer": ["paneer", "spinach", "onion", "tomato"],
    "Mix Dal": ["toor dal", "moong dal", "masoor dal", "onion", "tomato"],
    "Chana Dal": ["chana dal", "onion", "tomato"],
    "Veg Handi": ["paneer", "carrot", "peas", "beans", "onion"],
    "Paneer Do Pyaza": ["paneer", "onion", "tomato"],
    "Lauki Kofta": ["bottle gourd", "onion", "tomato"],
    "Paneer Butter Masala": ["paneer", "tomato", "butter", "cream", "onion"],
    "Aloo Beans": ["potato", "beans", "onion"],
    "Lemon Rice": ["rice", "lemon", "curry leaves"],
    "Veg Kurma": ["carrot", "beans", "peas", "onion", "tomato"],
    "Veg Do Pyaza": ["onion", "capsicum", "tomato"],
    "Aloo Methi": ["potato", "fenugreek leaves", "onion"],
    "Chole": ["chickpeas", "onion", "tomato", "ginger", "garlic"],
    "Baingan Bharta": ["brinjal", "onion", "tomato"],
    "Aloo Matar": ["potato", "peas", "onion", "tomato"],
    "Shahi Paneer": ["paneer", "onion", "tomato", "cream"],
    "Panchmel Dal": ["toor dal", "chana dal", "moong dal", "masoor dal", "urad dal"],
    "Aloo Palak": ["potato", "spinach", "onion", "tomato"],
    "Paneer Bhurji": ["paneer", "onion", "tomato"],
    "Veg Malai Curry": ["peas", "carrot", "onion", "cream"],
    "Moong Dal Fry": ["moong dal", "onion", "tomato"],
    "Aloo Tamatar": ["potato", "tomato", "onion"],
    "Soya Pulao": ["rice", "soya chunks", "onion"],
    "Curd Rice": ["rice", "curd"],
    "Aloo Capsicum": ["potato", "capsicum", "onion", "tomato"],
    "Tomato Rice": ["rice", "tomato", "onion"],
    "Lauki Tamatar": ["bottle gourd", "tomato"],
    "Tori Chana Dal": ["ridge gourd", "chana dal", "onion"],
    "Turai Sabzi": ["ridge gourd", "onion", "tomato"],
    "Dal Makhani": ["black lentils", "rajma", "butter", "cream"],
    "Aloo Baingan": ["potato", "brinjal", "onion", "tomato"],
    "Khichdi": ["rice", "moong dal", "ghee"],
    "Egg Fried Rice": ["rice", "egg", "onion"],
    "Parwal Aloo": ["parwal", "potato", "onion"],
    "Vegetable Khichdi": ["rice", "moong dal", "carrot", "peas"],
    "Veg Kolhapuri": ["carrot", "peas", "beans", "capsicum", "onion"],
    "Veg Bhuna Masala": ["onion", "tomato", "peas", "carrot"],
    "Veg Biryani": ["rice", "carrot", "peas", "beans", "onion"],
    "Dal Khichdi": ["rice", "toor dal", "onion"],
    "Veg Pulao": ["rice", "carrot", "peas", "onion"],
    "Matar Paneer": ["paneer", "peas", "tomato", "onion"],
    "Coconut Rice": ["rice", "coconut", "curry leaves"],
    "Aloo Jeera": ["potato", "cumin seeds", "oil"],
    "Tawa Pulao": ["rice", "onion", "tomato", "capsicum"],
}

# Instead of shuffling the whole dict, shuffle the list of names
recipe_names = list(recipes.items())
random.shuffle(recipe_names)
recipes = dict(recipe_names)